# Generated by Django 4.2.20 on 2025-05-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_fooditem_image_fooditem_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='image_url',
        ),
    ]
