# Generated by Django 4.2.20 on 2025-05-03 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_fooditem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
